# Configuration
config:
  # MD013 - line-length
  line_length:
    line_length: 120
    code_blocks: false
    tables: false
  html:
    allowed_elements:
      - div
      - br
      - hr

globs:
  - "**/*.md"

ignores:
  - "tmp/"
  - "paper.md"

fix: true
