# Configuration from TopoStats run completed : 2024-12-02 15:57:34
# For more information on configuration and how to use it:
# https://afm-spm.github.io/TopoStats/main/configuration.html
base_dir: /Volumes/shared/pyne_group/Shared/AFM_Data/Knots_and_Catenanes/Max's Reffined Data/all_samples
cores: 6
disordered_tracing:
  mask_smoothing_params:
    dilation_iterations: null
    gaussian_sigma: null
    holearea_min_max: [5, 20]
  min_skeleton_size: 10
  pad_width: 1
  pruning_params: {height_threshold: null, max_length: 10.0, method: topostats, method_outlier: mean_abs,
    method_values: mid}
  run: true
  skeletonisation_params: {height_bias: 0.6, method: topostats}
file_ext: .spm
filter:
  gaussian_mode: nearest
  gaussian_size: 1.1
  otsu_threshold_multiplier: 1.0
  remove_scars: {max_scar_width: 4, min_scar_length: 16, removal_iterations: 2, run: false,
    threshold_high: 0.666, threshold_low: 0.25}
  row_alignment_quantile: 0.5
  run: true
  threshold_absolute: {above: 1.0, below: -1.0}
  threshold_method: std_dev
  threshold_std_dev: {above: 1.0, below: 10.0}
grains:
  absolute_area_threshold:
    above: [2000, null]
    below: [null, null]
  direction: above
  otsu_threshold_multiplier: 1.0
  remove_edge_intersecting_grains: true
  run: true
  smallest_grain_size_nm2: 50
  threshold_absolute: {above: 0.7, below: -1.0}
  threshold_method: absolute
  threshold_std_dev: {above: 1.0, below: 10.0}
  unet_config: {grain_crop_padding: 20, lower_norm_bound: -1.0, model_path: /Volumes/shared/pyne_group/Shared/machine-learning/all_unet_models/catsnet_model.keras,
    upper_norm_bound: 5.0}
grainstats: {cropped_size: -1, edge_detection_method: binary_erosion, extract_height_profile: false,
  run: true}
loading: {channel: Height}
log_level: info
nodestats: {branch_pairing_length: 20.0, node_extend_dist: 14.0, node_joining_length: 7.0,
  pad_width: 1, pair_odd_branches: true, run: true}
ordered_tracing: {ordering_method: nodestats, pad_width: 1, run: true}
output_dir: /Volumes/shared/pyne_group/Shared/AFM_Data/Knots_and_Catenanes/Max's Reffined Data/laura_processed
plotting:
  axes: false
  cmap: null
  colorbar: false
  histogram_log_axis: false
  image_set: all
  mask_cmap: blue_purple_green
  num_ticks: [null, null]
  pixel_interpolation: null
  run: true
  savefig_dpi: 200
  savefig_format: tiff
  style: topostats.mplstyle
  zrange: [-2, 4]
splining: {method: rolling_window, rolling_window_size: 5e-09, run: true, spline_circular_smoothing: 5.0,
  spline_degree: 3, spline_linear_smoothing: 5.0, spline_step_size: 7e-09}
summary_stats: {config: null, run: false}
