# Configuration from TopoStats run completed : 2024-09-24 19:24:58
# For more information on configuration and how to use it:
# https://afm-spm.github.io/TopoStats/main/configuration.html
base_dir: /Users/laura/TopoStats/libby
cores: 2
dnatracing: {min_skeleton_size: 10, pad_width: 1, run: true, skeletonisation_method: topostats,
  spline_circular_smoothing: 0.0, spline_linear_smoothing: 5.0, spline_step_size: 7e-09}
file_ext: .spm
filter:
  gaussian_mode: nearest
  gaussian_size: 1.0121397464510862
  otsu_threshold_multiplier: 1.0
  remove_scars: {max_scar_width: 4, min_scar_length: 16, removal_iterations: 2, run: false,
    threshold_high: 0.666, threshold_low: 0.25}
  row_alignment_quantile: 0.5
  run: true
  threshold_absolute: {above: 1.0, below: -1.0}
  threshold_method: std_dev
  threshold_std_dev: {above: 1.0, below: 10.0}
grains:
  absolute_area_threshold:
    above: [300, 30000]
    below: [null, null]
  direction: above
  otsu_threshold_multiplier: 1.0
  remove_edge_intersecting_grains: true
  run: true
  smallest_grain_size_nm2: 50
  threshold_absolute: {above: 1.0, below: -1.0}
  threshold_method: std_dev
  threshold_std_dev: {above: 1.0, below: 10.0}
  unet_config: {grain_crop_padding: 2, lower_norm_bound: -1.0, model_path: /Users/laura/Desktop/models/shelterin_multiclass_model2024-08-30_10-28-33.keras,
    upper_norm_bound: 6.0}
grainstats: {cropped_size: 40.0, edge_detection_method: binary_erosion, extract_height_profile: true,
  run: true}
loading: {channel: Height}
log_level: info
output_dir: /Users/laura/TopoStats/libby/output
plotting:
  axes: true
  cmap: null
  colorbar: true
  histogram_log_axis: false
  image_set: all
  mask_cmap: blu
  num_ticks: [null, null]
  pixel_interpolation: null
  run: true
  savefig_dpi: null
  savefig_format: null
  style: topostats.mplstyle
  zrange: [-2, 7]
summary_stats: {config: null, run: true}
