# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "2.0.1.dev424+g0f9db72.d20230315"
__version_tuple__ = version_tuple = (2, 0, 1, "dev424", "g0f9db72.d20230315")
