# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "2.0.1.dev397+g1888c68.d20230314"
__version_tuple__ = version_tuple = (2, 0, 1, "dev397", "g1888c68.d20230314")
