# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = "2.0.1.dev369+g21461a8.d20230301"
__version_tuple__ = version_tuple = (2, 0, 1, "dev369", "g21461a8.d20230301")
