base_dir: ./tests/
output_dir: ./output
save_plots: true
warnings: ignore
cores: 4
quiet: false
file_ext: .spm
channel: Height
amplify_level: 1.0
threshold_method: otsu
colormap: nanoscope
grains:
  gaussian_size: 2.0
  gaussian_mode: nearest
  threshold_multiplier: 1.7
  minimum_grain_size: 800
  background: 0.0
