base_dir: ./tests/
output_dir: ./output
save_plots: true
warnings: ignore
cores: 4
quiet: false
file_ext: .spm
channel: Height
amplify_level: 1.0
filter:
  threshold:
    method: std_dev # Options : otsu, std_dev, absolute
    otsu_multiplier: 1.0
    std_dev: 1.0
    absolute:
      - 1
      - -1
grains:
  gaussian_size: 2.0 
  gaussian_mode: nearest
  absolute_smallest_grain_size: 100
  background: 0.0
  zrange: [0, 3] # List of low and high height range
  mask_direction: upper # Options: upper, lower (currently only applied to thresh+mask image)
  save_cropped_grains: True
  threshold:
    method: std_dev # Options : otsu, std_dev, absolute
    otsu_multiplier: 1.0
    std_dev: 1.0
    absolute:
      - 1
      - -1
plotting:
  save: True
  image_set: core # Options : all, core
  colorbar: True
  cmap: nanoscope # Options : nanoscope, afmhot
