base_dir: ./tests
output_dir: ./output
warnings: ignore
cores: 4
quiet: false
file_ext: .spm
filter:
  run: true # Options : true, false
  channel: Height
  amplify_level: 1.0
  threshold_method: std_dev # Options : otsu, std_dev, absolute
  otsu_threshold_multiplier: 1.0
  threshold_std_dev: 1.0
  threshold_absolute_lower: -1.0
  threshold_absolute_upper: 1.0
grains:
  run: true # Options : true, false
  gaussian_size: 2.0
  gaussian_mode: nearest
  absolute_smallest_grain_size: 100
  threshold_method: std_dev # Options : otsu, std_dev, absolute
  otsu_threshold_multiplier: 1.0
  threshold_std_dev: 1.0
  threshold_absolute_lower: -1.0
  threshold_absolute_upper: 1.0
  direction: upper # Options: upper, lower, both (defines whether to look for grains above or below thresholds or both)
  background: 0.0
grainstats:
  run: true # Options : true, false
  cropped_size: 40 # Length (in nm) of square cropped images (can take -1 for grain-sized box)
  save_cropped_grains: true # Options : true, false
dnatracing:
  run: true # Options : true, false
plotting:
  run: true # Options : true, false
  save_format: png # Options : see https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.savefig.html
  image_set: all  # Options : all, core
  zrange: [0, 3] # low and high height range for core images (can take [null, null])
  colorbar: true  # Options : true, false
  axes: true # Options : true, false (due to off being a bool when parsed)
  cmap: nanoscope # Options : nanoscope, afmhot
