file: ./output/all_statistics.csv
# Consider compatibility for multiple (or at least two) files
output_dir: ./plots
extension: '.png'
plots:
  plot_1:
    data:
    # Need to add option to filter the data, eg by 'Circular' == False
    group: None
    # e.g. Setting group argument: 'Basename'
    parameter: 'area'
    # Available parameters:
    plottype: histogram
    # Available types: KDE, histogram, violin, dist
    color: blue
    nm: True
    xmin:
    xmax:
    ymin:
    ymax:
  plot_2:
    data:
    group:
    parameter: 'height_max'
    plottype: KDE
    color: red
    nm: True
    xmin:
    xmax:
    ymin:
    ymax:
