file: ./output/all_statistics.csv
file2: null
# Consider compatibility for multiple (or at least two) files
output_dir: ./plots
extension: '.png'
plots:
  plot_1:
    data:
    # Need to add option to filter the data, eg by 'Circular' == False
    group: null
    # e.g. Setting group argument: 'Basename'
    parameter: 'area'
    # Available parameters:
    plottype: histogram2
    # Available types: KDE, histogram, violin, dist, histogram2, dist2
    color: blue
    nm: False
    xmin:
    xmax:
    ymin:
    ymax:
    bins_number: 20
    bins_start:
    bins_end:
  plot_2:
    data:
    group:
    parameter: 'height_max'
    plottype: KDE
    color: red
    nm: True
    xmin:
    xmax:
    ymin:
    ymax:
    bins_number:
    bins_start:
    bins_end:
