name: Container build and test

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          tags: afmspm/topostats:x
          push: true
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Pull container
        uses: docker://afmspm/topostats:x
      - name: Install topostats
        run: |
          pip install -e .
      - name: Smoke Test
        run: |
          python -m topostats
