name: Smoke Test

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    name: Smoke Test
    runs-on: ubuntu-latest
    container: afmspm/topostats:wip
    steps:
      - uses: actions/checkout@v2
      - name: Run TopoStats
        run: |
          pwd
          xvfb-run python pygwytracing.py