name: Smoke Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Smoke Test
    runs-on: ubuntu-latest
    container: afmspm/gwyddion-python:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install package and dependencies
        run: |
          apt-get update
          apt-get install -y python-matplotlib python-pandas python-pip python-seaborn python-skimage
      - name: Run TopoStats
        run: |
          pwd
          xvfb-run python pygwytracing.py